#!/bin/bash

echo "☁️  GOOGLE CLOUD RUN DEPLOYMENT GUIDE"
echo "====================================="
echo ""
echo "🎯 Why Google Cloud Run is PERFECT for you:"
echo "  ✅ MOST generous free tier (2M requests/month!)"
echo "  ✅ Up to 1GB RAM per instance (vs Railway's 512MB)"
echo "  ✅ Auto-scales to ZERO (pay only when used)"
echo "  ✅ Fastest cold start times"
echo "  ✅ No time limits (Railway has usage hours)"
echo "  ✅ Global deployment"
echo ""

echo "💰 FREE TIER LIMITS:"
echo "  • 2,000,000 requests per month"
echo "  • 400,000 GB-seconds compute time"
echo "  • 1GB memory maximum"
echo "  • 200,000 GHz-seconds CPU time"
echo "  • Basically unlimited for personal projects!"
echo ""

echo "📋 Files ready for Google Cloud:"
echo "  ✅ Dockerfile - Optimized container setup"
echo "  ✅ .gcloudignore - Deployment file filtering"
echo "  ✅ main.py - Cloud Run optimized FastAPI app"
echo "  ✅ requirements.txt - All dependencies"
echo ""

echo "🚀 DEPLOYMENT STEPS:"
echo ""
echo "1️⃣  Install Google Cloud CLI:"
echo "    • Visit: https://cloud.google.com/sdk/docs/install"
echo "    • Download installer for macOS"
echo "    • Run: ./google-cloud-sdk/install.sh"
echo "    • Restart terminal"
echo ""

echo "2️⃣  Setup Google Cloud (one-time):"
echo "    gcloud auth login"
echo "    gcloud config set project [YOUR-PROJECT-ID]"
echo "    gcloud services enable run.googleapis.com"
echo "    gcloud services enable cloudbuild.googleapis.com"
echo ""

echo "3️⃣  Deploy your app (single command!):"
echo "    gcloud run deploy word-vector-api \\"
echo "      --source . \\"
echo "      --platform managed \\"
echo "      --region us-central1 \\"
echo "      --allow-unauthenticated \\"
echo "      --memory 1Gi \\"
echo "      --cpu 1 \\"
echo "      --timeout 3600"
echo ""

echo "⏱️  Deployment timeline:"
echo "    • First deployment: 5-8 minutes"
echo "    • Subsequent deploys: 2-3 minutes"
echo "    • Cold start: 10-30 seconds (much faster than others!)"
echo "    • Warm requests: <50ms"
echo ""

echo "🌐 After deployment:"
echo "    • You'll get a URL like: https://word-vector-api-xxx-uc.a.run.app"
echo "    • Beautiful web interface at root URL"
echo "    • API docs at /docs"
echo "    • Health check at /health"
echo ""

echo "💡 Management commands:"
echo "    # View your services"
echo "    gcloud run services list"
echo ""
echo "    # View logs"
echo "    gcloud run services logs read word-vector-api"
echo ""
echo "    # Update service"
echo "    gcloud run deploy word-vector-api --source ."
echo ""
echo "    # Delete service (if needed)"
echo "    gcloud run services delete word-vector-api"
echo ""

echo "🎉 Benefits over Railway/Render:"
echo "  • NO sleep/wake delays"
echo "  • MUCH more generous free limits"
echo "  • Faster performance"
echo "  • Better error handling"
echo "  • Enterprise-grade infrastructure"
echo "  • Google's global CDN"
echo ""

echo "🆘 Need a Google Cloud project?"
echo "    1. Go to console.cloud.google.com"
echo "    2. Click 'New Project'"
echo "    3. Name it 'word-vector-api'"
echo "    4. Note the Project ID"
echo ""

echo "Ready to deploy? Your Word Vector API will be BLAZING fast! 🚀"
